services:
  collector:
    networks:
      - collector_net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ADDITIONAL_REPOS=github.com/martinjt/resourceattrtocontextconnector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - COLLECTOR_LOCATION="local ${USER}"
      - COLLECTOR_NAME=holly

networks:
  collector_net:
    driver: bridge
