services:
  collector:
    networks:
      - collector_net
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}

networks:
  collector_net:
    driver: bridge