services:
  collector:
    networks:
      - collector_net
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ADDITIONAL_REPOS=github.com/martinjt/resourceattrtocontextconnector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - COLLECTOR_LOCATION=local-${USER}
      - COLLECTOR_NAME=holly

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    networks:
      - collector_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  collector_net:
    driver: bridge
