AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-app

Resources:
  API:
    Type: AWS::Serverless::Function 
    Properties:
      Description: "API Gateway endpoint URL"
      Handler: api
      Runtime: go1.x
      Timeout: 10
      Events:
        RootResource:
          PayloadFormatVersion: '2.0'
          Type: HttpApi
          Properties:
            Path: /api/{proxy+}
            Method: ANY
      Environment:
        Variables:
          openai_key:
          OTEL_EXPORTER_OTLP_ENDPOINT:
          OTEL_EXPORTER_OTLP_INSECURE:

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
