
# To make this work, install the VSCode extension humau:rest-client
# then a little "Send Request" link appears above each GET and POST.

# also, copy .env.example to .env and populate a Honeycomb API key
# that the person would have entered into the quiz
# Otherwise you'll get internal server errors from our brilliant function

@AttendeeAPIKey = {{$dotenv ATTENDEE_API_KEY}} 

POST {{hostname}}/api/queryData
X-Honeycomb-Api-Key: {{AttendeeAPIKey}}
X-Observaquiz-Execution-Id: 1234

{
    "attendee_api_key": "{{AttendeeAPIKey}}",
    "dataset_slug": "observaquiz-bff",
    "query": {
        "time_range": 600,
        "granularity": 0,
        "breakdowns": [],
        "calculations": [
            {
                "op": "COUNT"
            }
        ],
        "limit": 100
    }
}
