
# To make this work, install the VSCode extension humau:rest-client
# then a little "Send Request" link appears above each GET and POST.

# also, copy .env.example to .env and populate a Honeycomb API key
# that the person would have entered into the quiz
# Otherwise you'll get internal server errors from our brilliant function

@AttendeeAPIKey = {{$dotenv ATTENDEE_API_KEY}} 

GET {{hostname}}/api/questions
X-Honeycomb-Api-Key: {{AttendeeAPIKey}}

###

POST {{hostname}}/api/questions/c954ab47-832c-43b1-b3de-d6f9ba995223/answer
X-Honeycomb-Api-Key: {{AttendeeAPIKey}}
Content-Type: application/json

{
    "answer": "it's about three pillars"
}
