
# To make this work, install the VSCode extension humau:rest-client
# then a little "Send Request" link appears above each GET and POST.

# also, copy .env.example to .env and populate a Honeycomb API key
# that the person would have entered into the quiz
# Otherwise you'll get internal server errors from our brilliant function

@AttendeeAPIKey = {{$dotenv ATTENDEE_API_KEY}} 

GET {{hostname}}/api/questions
X-Honeycomb-Api-Key: {{AttendeeAPIKey}}

### 

# what is the difference btwn apm and o11y
POST {{hostname}}/api/questions/c7a568b4-5fd0-4f88-9235-0b5d507e484f/answer
X-Honeycomb-Api-Key: {{AttendeeAPIKey}}
Content-Type: application/json

{
    "answer": "Observability is a superset of monitoring, and is a way of thinking about systems that emphasizes the ability to understand what is happening inside a system from the outside."
}

### what do you get from great o11y

POST {{hostname}}/api/questions/7db42ae5-d4a7-41f1-bfc1-4fc92ad9d3ca/answer
X-Honeycomb-Api-Key: {{AttendeeAPIKey}}
Content-Type: application/json

{
    "answer": "You get a better developer experience"
}

### unfound question

POST {{hostname}}/api/questions/ffaaffffaff/answer
X-Honeycomb-Api-Key: {{AttendeeAPIKey}}
Content-Type: application/json

{
    "answer": "You get a better developer experience"
}
